services:
  moviepilot:
    image: docker.io/jxxghp/moviepilot-v2:${VERSION}
    container_name: moviepilot
    network_mode: host
    volumes:
      - ${TRIM_PKGVAR:?}/config:/config
      - ${TRIM_PKGVAR:?}/core:/moviepilot
      - ${wizard_media_dir:-${TRIM_PKGVAR:?}/media}:/media
      - ${wizard_download_dir:-${TRIM_PKGVAR:?}/downloads}:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
      - UMASK=000
      - NGINX_PORT=4000
      - PORT=4001
      - SUPERUSER=${wizard_superuser:-admin}
      - SUPERUSER_PASSWORD=${wizard_password:-password}
    restart: unless-stopped
