services:
  moviepilot:
    image: __DOCKER_MIRROR__jxxghp/moviepilot-v2:${VERSION}
    container_name: moviepilot
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/config
      - ${TRIM_PKGVAR:?}/core:/moviepilot
      - ${wizard_media_dir:-${TRIM_PKGVAR:?}/media}:/media
      - ${wizard_download_dir:-${TRIM_PKGVAR:?}/downloads}:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
      - UMASK=022
      - NGINX_PORT=3000
      - PORT=3001
      - GITHUB_PROXY=https://gh-proxy.com/
      - SUPERUSER=admin
      - SUPERUSER_PASSWORD=${wizard_password:-password}
    restart: unless-stopped
